packages:
  - 'apps/*'
  - 'packages/*'

engineStrict: true

allowBuilds:
  '@swc/core': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - prettier@3.9.9
  - turbo@2.11.3
